#!/bin/sh
set -e

[ "$1" ] || exit 1

# shellcheck source=../lib/lab.sh
. ./lib/lab.sh

case "$1" in
	vlab_lan)
		_lan_up "$1"
		;;
	*_lan)
		modem_name=${1%%_lan}
		_modem_up "$modem_name"
		;;
	*) _log_error "Invalid interface name: $1" ;;
esac
