#!/bin/sh

if [ -z "$1" ]; then
    echo "Error: no interface specified"
    exit 1
fi

DOCKER_BRIDGE_ID=$(docker network ls | grep vLab | awk '{ print $1 }')
DOCKER_BRIDGE="br-$DOCKER_BRIDGE_ID"

FORWARD=$(cat /proc/sys/net/ipv4/ip_forward)
[ "$FORWARD" != 1 ] && sysctl -w net.ipv4.ip_forward=1

ip tuntap add "$1" mode tap
ip link set "$1" up
sleep 0.5s
ip link set "$1" master "$DOCKER_BRIDGE"
