#!/bin/sh
set -e

# shellcheck source=../lib/lab.sh
. lib/lab.sh

modem_name=$1
wan_ip=$2

host_gw=$(ip -4 -o addr show vlan | awk '{ print $4 }' | cut -d'/' -f1)
[ "$host_gw" ] || _log_error "Failed to find host gateway"
_log_info "Host gateway found: $host_gw"

_log_info "Creating veth interface"
pseudo_random_name=$(date +%N)
ip link add "$modem_name" type veth peer name "$pseudo_random_name"
ip link set "$modem_name" up
ip link set "$pseudo_random_name" netns "$modem_name"

_log_info "Configuring the network in the network namespace"
ip -n "$modem_name" link set "$pseudo_random_name" name wan
ip -n "$modem_name" link set lo up
ip -n "$modem_name" link set wan up
ip -n "$modem_name" addr add "$wan_ip" dev wan
ip -n "$modem_name" route add "$host_gw" dev wan scope link
ip -n "$modem_name" route add default via "$host_gw"

_log_info "Adding route on the host"
ip route add "$wan_ip" dev "$modem_name" scope link table 100
